package com.bookstore.entity;
// Generated Aug 5, 2020 8:24:04 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity

@NamedQueries({
	@NamedQuery(name="Users.findAll",query="select u from Users u order by u.fullName"),
	@NamedQuery(name="Users.count",query="Select Count(*) from Users u"),
	@NamedQuery(name="Users.findByEmail",query="select u from Users u where u.email = :email"),
	@NamedQuery(name="Users.checkLogin",query="select u from Users u where u.email= :email and u.password= :password")
})

@Table(name = "users", catalog = "book_store")
public class Users implements java.io.Serializable {

	private int userId;
	private String email;
	private String password;
	private String fullName;

	public Users() {
	}

	public Users(int userId, String email, String password, String fullName) {
		this.userId = userId;
		this.email = email;
		this.password = password;
		this.fullName = fullName;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		System.out.print("I m user model class");
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 16)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "full_name", nullable = false, length = 30)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

}
